export interface Verse {
  number: number;
  text: string;
}

export interface Surah {
  number: number;
  nameArabic: string;
  nameTranslit: string;
  nameFr: string;
  versesCount: number;
  verses: Verse[];
}

export const SURAHS: Surah[] = [
  {
    number: 1,
    nameArabic: "الْفَاتِحَة",
    nameTranslit: "Al-Fatiha",
    nameFr: "L'Ouverture",
    versesCount: 7,
    verses: [
      { number: 1, text: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ" },
      { number: 2, text: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ" },
      { number: 3, text: "الرَّحْمَٰنِ الرَّحِيمِ" },
      { number: 4, text: "مَالِكِ يَوْمِ الدِّينِ" },
      { number: 5, text: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ" },
      { number: 6, text: "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ" },
      { number: 7, text: "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ" },
    ],
  },
  {
    number: 2,
    nameArabic: "الْبَقَرَة",
    nameTranslit: "Al-Baqara",
    nameFr: "La Vache",
    versesCount: 286,
    verses: [
      { number: 1, text: "الٓمٓ" },
      { number: 2, text: "ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ" },
      { number: 3, text: "الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ وَيُقِيمُونَ الصَّلَاةَ وَمِمَّا رَزَقْنَاهُمْ يُنفِقُونَ" },
      { number: 4, text: "وَالَّذِينَ يُؤْمِنُونَ بِمَا أُنزِلَ إِلَيْكَ وَمَا أُنزِلَ مِن قَبْلِكَ وَبِالْآخِرَةِ هُمْ يُوقِنُونَ" },
      { number: 5, text: "أُولَٰئِكَ عَلَىٰ هُدًى مِّن رَّبِّهِمْ ۖ وَأُولَٰئِكَ هُمُ الْمُفْلِحُونَ" },
      { number: 255, text: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ" },
      { number: 285, text: "آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّن رُّسُلِهِ ۚ وَقَالُوا سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ" },
      { number: 286, text: "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ ۗ رَبَّنَا لَا تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا ۚ رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا ۚ رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ ۖ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا ۚ أَنتَ مَوْلَانَا فَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ" },
    ],
  },
  {
    number: 3,
    nameArabic: "آلِ عِمْرَان",
    nameTranslit: "Ali 'Imran",
    nameFr: "La Famille d'Imran",
    versesCount: 200,
    verses: [
      { number: 1, text: "الٓمٓ" },
      { number: 2, text: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ" },
      { number: 3, text: "نَزَّلَ عَلَيْكَ الْكِتَابَ بِالْحَقِّ مُصَدِّقًا لِّمَا بَيْنَ يَدَيْهِ وَأَنزَلَ التَّوْرَاةَ وَالْإِنجِيلَ" },
    ],
  },
  {
    number: 4,
    nameArabic: "النِّسَاء",
    nameTranslit: "An-Nisa",
    nameFr: "Les Femmes",
    versesCount: 176,
    verses: [
      { number: 1, text: "يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمُ الَّذِي خَلَقَكُم مِّن نَّفْسٍ وَاحِدَةٍ وَخَلَقَ مِنْهَا زَوْجَهَا وَبَثَّ مِنْهُمَا رِجَالًا كَثِيرًا وَنِسَاءً ۚ وَاتَّقُوا اللَّهَ الَّذِي تَسَاءَلُونَ بِهِ وَالْأَرْحَامَ ۚ إِنَّ اللَّهَ كَانَ عَلَيْكُمْ رَقِيبًا" },
    ],
  },
  {
    number: 5,
    nameArabic: "الْمَائِدَة",
    nameTranslit: "Al-Ma'ida",
    nameFr: "La Table Servie",
    versesCount: 120,
    verses: [
      { number: 1, text: "يَا أَيُّهَا الَّذِينَ آمَنُوا أَوْفُوا بِالْعُقُودِ ۚ أُحِلَّتْ لَكُم بَهِيمَةُ الْأَنْعَامِ إِلَّا مَا يُتْلَىٰ عَلَيْكُمْ غَيْرَ مُحِلِّي الصَّيْدِ وَأَنتُمْ حُرُمٌ ۗ إِنَّ اللَّهَ يَحْكُمُ مَا يُرِيدُ" },
    ],
  },
  {
    number: 6,
    nameArabic: "الْأَنْعَام",
    nameTranslit: "Al-An'am",
    nameFr: "Les Bestiaux",
    versesCount: 165,
    verses: [
      { number: 1, text: "الْحَمْدُ لِلَّهِ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ وَجَعَلَ الظُّلُمَاتِ وَالنُّورَ ۖ ثُمَّ الَّذِينَ كَفَرُوا بِرَبِّهِمْ يَعْدِلُونَ" },
    ],
  },
  {
    number: 7,
    nameArabic: "الْأَعْرَاف",
    nameTranslit: "Al-A'raf",
    nameFr: "Les Hauteurs",
    versesCount: 206,
    verses: [
      { number: 1, text: "الٓمٓصٓ" },
      { number: 2, text: "كِتَابٌ أُنزِلَ إِلَيْكَ فَلَا يَكُن فِي صَدْرِكَ حَرَجٌ مِّنْهُ لِتُنذِرَ بِهِ وَذِكْرَىٰ لِلْمُؤْمِنِينَ" },
    ],
  },
  {
    number: 8,
    nameArabic: "الْأَنْفَال",
    nameTranslit: "Al-Anfal",
    nameFr: "Le Butin",
    versesCount: 75,
    verses: [
      { number: 1, text: "يَسْأَلُونَكَ عَنِ الْأَنفَالِ ۖ قُلِ الْأَنفَالُ لِلَّهِ وَالرَّسُولِ ۖ فَاتَّقُوا اللَّهَ وَأَصْلِحُوا ذَاتَ بَيْنِكُمْ ۖ وَأَطِيعُوا اللَّهَ وَرَسُولَهُ إِن كُنتُم مُّؤْمِنِينَ" },
    ],
  },
  {
    number: 9,
    nameArabic: "التَّوْبَة",
    nameTranslit: "At-Tawba",
    nameFr: "Le Repentir",
    versesCount: 129,
    verses: [
      { number: 1, text: "بَرَاءَةٌ مِّنَ اللَّهِ وَرَسُولِهِ إِلَى الَّذِينَ عَاهَدتُّم مِّنَ الْمُشْرِكِينَ" },
    ],
  },
  {
    number: 10,
    nameArabic: "يُونُس",
    nameTranslit: "Yunus",
    nameFr: "Jonas",
    versesCount: 109,
    verses: [
      { number: 1, text: "الٓرٓ ۚ تِلْكَ آيَاتُ الْكِتَابِ الْحَكِيمِ" },
    ],
  },
  {
    number: 11,
    nameArabic: "هُود",
    nameTranslit: "Hud",
    nameFr: "Hud",
    versesCount: 123,
    verses: [
      { number: 1, text: "الٓرٓ ۚ كِتَابٌ أُحْكِمَتْ آيَاتُهُ ثُمَّ فُصِّلَتْ مِن لَّدُنْ حَكِيمٍ خَبِيرٍ" },
    ],
  },
  {
    number: 12,
    nameArabic: "يُوسُف",
    nameTranslit: "Yusuf",
    nameFr: "Joseph",
    versesCount: 111,
    verses: [
      { number: 1, text: "الٓرٓ ۚ تِلْكَ آيَاتُ الْكِتَابِ الْمُبِينِ" },
      { number: 2, text: "إِنَّا أَنزَلْنَاهُ قُرْآنًا عَرَبِيًّا لَّعَلَّكُمْ تَعْقِلُونَ" },
    ],
  },
  {
    number: 13,
    nameArabic: "الرَّعْد",
    nameTranslit: "Ar-Ra'd",
    nameFr: "Le Tonnerre",
    versesCount: 43,
    verses: [
      { number: 1, text: "الٓمٓرٓ ۚ تِلْكَ آيَاتُ الْكِتَابِ ۗ وَالَّذِي أُنزِلَ إِلَيْكَ مِن رَّبِّكَ الْحَقُّ وَلَٰكِنَّ أَكْثَرَ النَّاسِ لَا يُؤْمِنُونَ" },
    ],
  },
  {
    number: 14,
    nameArabic: "إِبْرَاهِيم",
    nameTranslit: "Ibrahim",
    nameFr: "Abraham",
    versesCount: 52,
    verses: [
      { number: 1, text: "الٓرٓ ۚ كِتَابٌ أَنزَلْنَاهُ إِلَيْكَ لِتُخْرِجَ النَّاسَ مِنَ الظُّلُمَاتِ إِلَى النُّورِ بِإِذْنِ رَبِّهِمْ إِلَىٰ صِرَاطِ الْعَزِيزِ الْحَمِيدِ" },
    ],
  },
  {
    number: 15,
    nameArabic: "الْحِجْر",
    nameTranslit: "Al-Hijr",
    nameFr: "Al-Hijr",
    versesCount: 99,
    verses: [
      { number: 1, text: "الٓرٓ ۚ تِلْكَ آيَاتُ الْكِتَابِ وَقُرْآنٍ مُّبِينٍ" },
    ],
  },
  {
    number: 16,
    nameArabic: "النَّحْل",
    nameTranslit: "An-Nahl",
    nameFr: "Les Abeilles",
    versesCount: 128,
    verses: [
      { number: 1, text: "أَتَىٰ أَمْرُ اللَّهِ فَلَا تَسْتَعْجِلُوهُ ۚ سُبْحَانَهُ وَتَعَالَىٰ عَمَّا يُشْرِكُونَ" },
    ],
  },
  {
    number: 17,
    nameArabic: "الْإِسْرَاء",
    nameTranslit: "Al-Isra",
    nameFr: "Le Voyage Nocturne",
    versesCount: 111,
    verses: [
      { number: 1, text: "سُبْحَانَ الَّذِي أَسْرَىٰ بِعَبْدِهِ لَيْلًا مِّنَ الْمَسْجِدِ الْحَرَامِ إِلَى الْمَسْجِدِ الْأَقْصَى الَّذِي بَارَكْنَا حَوْلَهُ لِنُرِيَهُ مِنْ آيَاتِنَا ۚ إِنَّهُ هُوَ السَّمِيعُ الْبَصِيرُ" },
    ],
  },
  {
    number: 18,
    nameArabic: "الْكَهْف",
    nameTranslit: "Al-Kahf",
    nameFr: "La Caverne",
    versesCount: 110,
    verses: [
      { number: 1, text: "الْحَمْدُ لِلَّهِ الَّذِي أَنزَلَ عَلَىٰ عَبْدِهِ الْكِتَابَ وَلَمْ يَجْعَل لَّهُ عِوَجًا" },
      { number: 2, text: "قَيِّمًا لِّيُنذِرَ بَأْسًا شَدِيدًا مِّن لَّدُنْهُ وَيُبَشِّرَ الْمُؤْمِنِينَ الَّذِينَ يَعْمَلُونَ الصَّالِحَاتِ أَنَّ لَهُمْ أَجْرًا حَسَنًا" },
    ],
  },
  {
    number: 19,
    nameArabic: "مَرْيَم",
    nameTranslit: "Maryam",
    nameFr: "Marie",
    versesCount: 98,
    verses: [
      { number: 1, text: "كٓهٓيٓعٓصٓ" },
    ],
  },
  {
    number: 20,
    nameArabic: "طه",
    nameTranslit: "Ta-Ha",
    nameFr: "Ta-Ha",
    versesCount: 135,
    verses: [
      { number: 1, text: "طٰهٰ" },
      { number: 2, text: "مَا أَنزَلْنَا عَلَيْكَ الْقُرْآنَ لِتَشْقَىٰ" },
    ],
  },
  {
    number: 21,
    nameArabic: "الْأَنبِيَاء",
    nameTranslit: "Al-Anbiya",
    nameFr: "Les Prophètes",
    versesCount: 112,
    verses: [
      { number: 1, text: "اقْتَرَبَ لِلنَّاسِ حِسَابُهُمْ وَهُمْ فِي غَفْلَةٍ مُّعْرِضُونَ" },
    ],
  },
  {
    number: 22,
    nameArabic: "الْحَج",
    nameTranslit: "Al-Hajj",
    nameFr: "Le Pèlerinage",
    versesCount: 78,
    verses: [
      { number: 1, text: "يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمْ ۚ إِنَّ زَلْزَلَةَ السَّاعَةِ شَيْءٌ عَظِيمٌ" },
    ],
  },
  {
    number: 23,
    nameArabic: "الْمُؤْمِنُون",
    nameTranslit: "Al-Mu'minun",
    nameFr: "Les Croyants",
    versesCount: 118,
    verses: [
      { number: 1, text: "قَدْ أَفْلَحَ الْمُؤْمِنُونَ" },
      { number: 2, text: "الَّذِينَ هُمْ فِي صَلَاتِهِمْ خَاشِعُونَ" },
    ],
  },
  {
    number: 24,
    nameArabic: "النُّور",
    nameTranslit: "An-Nur",
    nameFr: "La Lumière",
    versesCount: 64,
    verses: [
      { number: 35, text: "اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ ۚ مَثَلُ نُورِهِ كَمِشْكَاةٍ فِيهَا مِصْبَاحٌ ۖ الْمِصْبَاحُ فِي زُجَاجَةٍ ۖ الزُّجَاجَةُ كَأَنَّهَا كَوْكَبٌ دُرِّيٌّ يُوقَدُ مِن شَجَرَةٍ مُّبَارَكَةٍ زَيْتُونَةٍ لَّا شَرْقِيَّةٍ وَلَا غَرْبِيَّةٍ يَكَادُ زَيْتُهَا يُضِيءُ وَلَوْ لَمْ تَمْسَسْهُ نَارٌ ۚ نُّورٌ عَلَىٰ نُورٍ ۗ يَهْدِي اللَّهُ لِنُورِهِ مَن يَشَاءُ ۚ وَيَضْرِبُ اللَّهُ الْأَمْثَالَ لِلنَّاسِ ۗ وَاللَّهُ بِكُلِّ شَيْءٍ عَلِيمٌ" },
    ],
  },
  {
    number: 25,
    nameArabic: "الْفُرْقَان",
    nameTranslit: "Al-Furqan",
    nameFr: "Le Critère",
    versesCount: 77,
    verses: [
      { number: 1, text: "تَبَارَكَ الَّذِي نَزَّلَ الْفُرْقَانَ عَلَىٰ عَبْدِهِ لِيَكُونَ لِلْعَالَمِينَ نَذِيرًا" },
    ],
  },
  {
    number: 26,
    nameArabic: "الشُّعَرَاء",
    nameTranslit: "Ash-Shu'ara",
    nameFr: "Les Poètes",
    versesCount: 227,
    verses: [
      { number: 1, text: "طٰسٓمٓ" },
    ],
  },
  {
    number: 27,
    nameArabic: "النَّمْل",
    nameTranslit: "An-Naml",
    nameFr: "Les Fourmis",
    versesCount: 93,
    verses: [
      { number: 1, text: "طٰسٓ ۚ تِلْكَ آيَاتُ الْقُرْآنِ وَكِتَابٍ مُّبِينٍ" },
    ],
  },
  {
    number: 28,
    nameArabic: "الْقَصَص",
    nameTranslit: "Al-Qasas",
    nameFr: "Le Récit",
    versesCount: 88,
    verses: [
      { number: 1, text: "طٰسٓمٓ" },
    ],
  },
  {
    number: 29,
    nameArabic: "الْعَنكَبُوت",
    nameTranslit: "Al-Ankabut",
    nameFr: "L'Araignée",
    versesCount: 69,
    verses: [
      { number: 1, text: "الٓمٓ" },
    ],
  },
  {
    number: 30,
    nameArabic: "الرُّوم",
    nameTranslit: "Ar-Rum",
    nameFr: "Les Byzantins",
    versesCount: 60,
    verses: [
      { number: 1, text: "الٓمٓ" },
    ],
  },
  {
    number: 31,
    nameArabic: "لُقْمَان",
    nameTranslit: "Luqman",
    nameFr: "Luqman",
    versesCount: 34,
    verses: [
      { number: 1, text: "الٓمٓ" },
    ],
  },
  {
    number: 32,
    nameArabic: "السَّجْدَة",
    nameTranslit: "As-Sajda",
    nameFr: "La Prosternation",
    versesCount: 30,
    verses: [
      { number: 1, text: "الٓمٓ" },
    ],
  },
  {
    number: 33,
    nameArabic: "الْأَحْزَاب",
    nameTranslit: "Al-Ahzab",
    nameFr: "Les Coalisés",
    versesCount: 73,
    verses: [
      { number: 1, text: "يَا أَيُّهَا النَّبِيُّ اتَّقِ اللَّهَ وَلَا تُطِعِ الْكَافِرِينَ وَالْمُنَافِقِينَ ۗ إِنَّ اللَّهَ كَانَ عَلِيمًا حَكِيمًا" },
    ],
  },
  {
    number: 34,
    nameArabic: "سَبَأ",
    nameTranslit: "Saba",
    nameFr: "Saba",
    versesCount: 54,
    verses: [
      { number: 1, text: "الْحَمْدُ لِلَّهِ الَّذِي لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ وَلَهُ الْحَمْدُ فِي الْآخِرَةِ ۚ وَهُوَ الْحَكِيمُ الْخَبِيرُ" },
    ],
  },
  {
    number: 35,
    nameArabic: "فَاطِر",
    nameTranslit: "Fatir",
    nameFr: "Le Créateur",
    versesCount: 45,
    verses: [
      { number: 1, text: "الْحَمْدُ لِلَّهِ فَاطِرِ السَّمَاوَاتِ وَالْأَرْضِ جَاعِلِ الْمَلَائِكَةِ رُسُلًا أُولِي أَجْنِحَةٍ مَّثْنَىٰ وَثُلَاثَ وَرُبَاعَ ۚ يَزِيدُ فِي الْخَلْقِ مَا يَشَاءُ ۚ إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ" },
    ],
  },
  {
    number: 36,
    nameArabic: "يٰس",
    nameTranslit: "Ya-Sin",
    nameFr: "Ya-Sin",
    versesCount: 83,
    verses: [
      { number: 1, text: "يٰسٓ" },
      { number: 2, text: "وَالْقُرْآنِ الْحَكِيمِ" },
      { number: 3, text: "إِنَّكَ لَمِنَ الْمُرْسَلِينَ" },
      { number: 4, text: "عَلَىٰ صِرَاطٍ مُّسْتَقِيمٍ" },
      { number: 5, text: "تَنزِيلَ الْعَزِيزِ الرَّحِيمِ" },
    ],
  },
  {
    number: 37,
    nameArabic: "الصَّافَّات",
    nameTranslit: "As-Saffat",
    nameFr: "Rangés en Rangs",
    versesCount: 182,
    verses: [
      { number: 1, text: "وَالصَّافَّاتِ صَفًّا" },
    ],
  },
  {
    number: 38,
    nameArabic: "ص",
    nameTranslit: "Sad",
    nameFr: "Sad",
    versesCount: 88,
    verses: [
      { number: 1, text: "صٓ ۚ وَالْقُرْآنِ ذِي الذِّكْرِ" },
    ],
  },
  {
    number: 39,
    nameArabic: "الزُّمَر",
    nameTranslit: "Az-Zumar",
    nameFr: "Les Groupes",
    versesCount: 75,
    verses: [
      { number: 1, text: "تَنزِيلُ الْكِتَابِ مِنَ اللَّهِ الْعَزِيزِ الْحَكِيمِ" },
    ],
  },
  {
    number: 40,
    nameArabic: "غَافِر",
    nameTranslit: "Ghafir",
    nameFr: "Le Pardonneur",
    versesCount: 85,
    verses: [
      { number: 1, text: "حٰمٓ" },
    ],
  },
  {
    number: 41,
    nameArabic: "فُصِّلَت",
    nameTranslit: "Fussilat",
    nameFr: "Exposées en Détail",
    versesCount: 54,
    verses: [
      { number: 1, text: "حٰمٓ" },
    ],
  },
  {
    number: 42,
    nameArabic: "الشُّورَى",
    nameTranslit: "Ash-Shura",
    nameFr: "La Consultation",
    versesCount: 53,
    verses: [
      { number: 1, text: "حٰمٓ" },
    ],
  },
  {
    number: 43,
    nameArabic: "الزُّخْرُف",
    nameTranslit: "Az-Zukhruf",
    nameFr: "Les Ornements",
    versesCount: 89,
    verses: [
      { number: 1, text: "حٰمٓ" },
    ],
  },
  {
    number: 44,
    nameArabic: "الدُّخَان",
    nameTranslit: "Ad-Dukhan",
    nameFr: "La Fumée",
    versesCount: 59,
    verses: [
      { number: 1, text: "حٰمٓ" },
    ],
  },
  {
    number: 45,
    nameArabic: "الْجَاثِيَة",
    nameTranslit: "Al-Jathiya",
    nameFr: "L'Agenouillée",
    versesCount: 37,
    verses: [
      { number: 1, text: "حٰمٓ" },
    ],
  },
  {
    number: 46,
    nameArabic: "الْأَحْقَاف",
    nameTranslit: "Al-Ahqaf",
    nameFr: "Les Dunes",
    versesCount: 35,
    verses: [
      { number: 1, text: "حٰمٓ" },
    ],
  },
  {
    number: 47,
    nameArabic: "مُحَمَّد",
    nameTranslit: "Muhammad",
    nameFr: "Muhammad",
    versesCount: 38,
    verses: [
      { number: 1, text: "الَّذِينَ كَفَرُوا وَصَدُّوا عَن سَبِيلِ اللَّهِ أَضَلَّ أَعْمَالَهُمْ" },
    ],
  },
  {
    number: 48,
    nameArabic: "الْفَتْح",
    nameTranslit: "Al-Fath",
    nameFr: "La Victoire",
    versesCount: 29,
    verses: [
      { number: 1, text: "إِنَّا فَتَحْنَا لَكَ فَتْحًا مُّبِينًا" },
    ],
  },
  {
    number: 49,
    nameArabic: "الْحُجُرَات",
    nameTranslit: "Al-Hujurat",
    nameFr: "Les Appartements",
    versesCount: 18,
    verses: [
      { number: 13, text: "يَا أَيُّهَا النَّاسُ إِنَّا خَلَقْنَاكُم مِّن ذَكَرٍ وَأُنثَىٰ وَجَعَلْنَاكُمْ شُعُوبًا وَقَبَائِلَ لِتَعَارَفُوا ۚ إِنَّ أَكْرَمَكُمْ عِندَ اللَّهِ أَتْقَاكُمْ ۚ إِنَّ اللَّهَ عَلِيمٌ خَبِيرٌ" },
    ],
  },
  {
    number: 50,
    nameArabic: "ق",
    nameTranslit: "Qaf",
    nameFr: "Qaf",
    versesCount: 45,
    verses: [
      { number: 1, text: "قٓ ۚ وَالْقُرْآنِ الْمَجِيدِ" },
    ],
  },
  {
    number: 51,
    nameArabic: "الذَّارِيَات",
    nameTranslit: "Adh-Dhariyat",
    nameFr: "Les Vents Dispersants",
    versesCount: 60,
    verses: [
      { number: 1, text: "وَالذَّارِيَاتِ ذَرْوًا" },
    ],
  },
  {
    number: 52,
    nameArabic: "الطُّور",
    nameTranslit: "At-Tur",
    nameFr: "Le Mont Sinaï",
    versesCount: 49,
    verses: [
      { number: 1, text: "وَالطُّورِ" },
    ],
  },
  {
    number: 53,
    nameArabic: "النَّجْم",
    nameTranslit: "An-Najm",
    nameFr: "L'Étoile",
    versesCount: 62,
    verses: [
      { number: 1, text: "وَالنَّجْمِ إِذَا هَوَىٰ" },
    ],
  },
  {
    number: 54,
    nameArabic: "الْقَمَر",
    nameTranslit: "Al-Qamar",
    nameFr: "La Lune",
    versesCount: 55,
    verses: [
      { number: 1, text: "اقْتَرَبَتِ السَّاعَةُ وَانشَقَّ الْقَمَرُ" },
    ],
  },
  {
    number: 55,
    nameArabic: "الرَّحْمَٰن",
    nameTranslit: "Ar-Rahman",
    nameFr: "Le Tout Miséricordieux",
    versesCount: 78,
    verses: [
      { number: 1, text: "الرَّحْمَٰنُ" },
      { number: 2, text: "عَلَّمَ الْقُرْآنَ" },
      { number: 3, text: "خَلَقَ الْإِنسَانَ" },
      { number: 4, text: "عَلَّمَهُ الْبَيَانَ" },
      { number: 13, text: "فَبِأَيِّ آلَاءِ رَبِّكُمَا تُكَذِّبَانِ" },
    ],
  },
  {
    number: 56,
    nameArabic: "الْوَاقِعَة",
    nameTranslit: "Al-Waqi'a",
    nameFr: "L'Événement",
    versesCount: 96,
    verses: [
      { number: 1, text: "إِذَا وَقَعَتِ الْوَاقِعَةُ" },
      { number: 2, text: "لَيْسَ لِوَقْعَتِهَا كَاذِبَةٌ" },
    ],
  },
  {
    number: 57,
    nameArabic: "الْحَدِيد",
    nameTranslit: "Al-Hadid",
    nameFr: "Le Fer",
    versesCount: 29,
    verses: [
      { number: 1, text: "سَبَّحَ لِلَّهِ مَا فِي السَّمَاوَاتِ وَالْأَرْضِ ۖ وَهُوَ الْعَزِيزُ الْحَكِيمُ" },
    ],
  },
  {
    number: 58,
    nameArabic: "الْمُجَادِلَة",
    nameTranslit: "Al-Mujadila",
    nameFr: "La Discussion",
    versesCount: 22,
    verses: [
      { number: 1, text: "قَدْ سَمِعَ اللَّهُ قَوْلَ الَّتِي تُجَادِلُكَ فِي زَوْجِهَا وَتَشْتَكِي إِلَى اللَّهِ وَاللَّهُ يَسْمَعُ تَحَاوُرَكُمَا ۚ إِنَّ اللَّهَ سَمِيعٌ بَصِيرٌ" },
    ],
  },
  {
    number: 59,
    nameArabic: "الْحَشْر",
    nameTranslit: "Al-Hashr",
    nameFr: "L'Exode",
    versesCount: 24,
    verses: [
      { number: 22, text: "هُوَ اللَّهُ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ ۖ عَالِمُ الْغَيْبِ وَالشَّهَادَةِ ۖ هُوَ الرَّحْمَٰنُ الرَّحِيمُ" },
      { number: 23, text: "هُوَ اللَّهُ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ الْمَلِكُ الْقُدُّوسُ السَّلَامُ الْمُؤْمِنُ الْمُهَيْمِنُ الْعَزِيزُ الْجَبَّارُ الْمُتَكَبِّرُ ۚ سُبْحَانَ اللَّهِ عَمَّا يُشْرِكُونَ" },
      { number: 24, text: "هُوَ اللَّهُ الْخَالِقُ الْبَارِئُ الْمُصَوِّرُ ۖ لَهُ الْأَسْمَاءُ الْحُسْنَىٰ ۚ يُسَبِّحُ لَهُ مَا فِي السَّمَاوَاتِ وَالْأَرْضِ ۖ وَهُوَ الْعَزِيزُ الْحَكِيمُ" },
    ],
  },
  {
    number: 60,
    nameArabic: "الْمُمْتَحَنَة",
    nameTranslit: "Al-Mumtahana",
    nameFr: "L'Éprouvée",
    versesCount: 13,
    verses: [
      { number: 1, text: "يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَتَّخِذُوا عَدُوِّي وَعَدُوَّكُمْ أَوْلِيَاءَ تُلْقُونَ إِلَيْهِم بِالْمَوَدَّةِ وَقَدْ كَفَرُوا بِمَا جَاءَكُم مِّنَ الْحَقِّ" },
    ],
  },
  {
    number: 61,
    nameArabic: "الصَّف",
    nameTranslit: "As-Saf",
    nameFr: "Le Rang",
    versesCount: 14,
    verses: [
      { number: 1, text: "سَبَّحَ لِلَّهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۖ وَهُوَ الْعَزِيزُ الْحَكِيمُ" },
    ],
  },
  {
    number: 62,
    nameArabic: "الْجُمُعَة",
    nameTranslit: "Al-Jumu'a",
    nameFr: "Le Vendredi",
    versesCount: 11,
    verses: [
      { number: 1, text: "يُسَبِّحُ لِلَّهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ الْمَلِكِ الْقُدُّوسِ الْعَزِيزِ الْحَكِيمِ" },
    ],
  },
  {
    number: 63,
    nameArabic: "الْمُنَافِقُون",
    nameTranslit: "Al-Munafiqun",
    nameFr: "Les Hypocrites",
    versesCount: 11,
    verses: [
      { number: 1, text: "إِذَا جَاءَكَ الْمُنَافِقُونَ قَالُوا نَشْهَدُ إِنَّكَ لَرَسُولُ اللَّهِ ۗ وَاللَّهُ يَعْلَمُ إِنَّكَ لَرَسُولُهُ وَاللَّهُ يَشْهَدُ إِنَّ الْمُنَافِقِينَ لَكَاذِبُونَ" },
    ],
  },
  {
    number: 64,
    nameArabic: "التَّغَابُن",
    nameTranslit: "At-Taghabun",
    nameFr: "La Déception Mutuelle",
    versesCount: 18,
    verses: [
      { number: 1, text: "يُسَبِّحُ لِلَّهِ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۖ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ ۖ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ" },
    ],
  },
  {
    number: 65,
    nameArabic: "الطَّلَاق",
    nameTranslit: "At-Talaq",
    nameFr: "Le Divorce",
    versesCount: 12,
    verses: [
      { number: 1, text: "يَا أَيُّهَا النَّبِيُّ إِذَا طَلَّقْتُمُ النِّسَاءَ فَطَلِّقُوهُنَّ لِعِدَّتِهِنَّ وَأَحْصُوا الْعِدَّةَ ۖ وَاتَّقُوا اللَّهَ رَبَّكُمْ" },
    ],
  },
  {
    number: 66,
    nameArabic: "التَّحْرِيم",
    nameTranslit: "At-Tahrim",
    nameFr: "L'Interdiction",
    versesCount: 12,
    verses: [
      { number: 1, text: "يَا أَيُّهَا النَّبِيُّ لِمَ تُحَرِّمُ مَا أَحَلَّ اللَّهُ لَكَ ۖ تَبْتَغِي مَرْضَاتَ أَزْوَاجِكَ ۚ وَاللَّهُ غَفُورٌ رَّحِيمٌ" },
    ],
  },
  {
    number: 67,
    nameArabic: "الْمُلْك",
    nameTranslit: "Al-Mulk",
    nameFr: "La Royauté",
    versesCount: 30,
    verses: [
      { number: 1, text: "تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ" },
      { number: 2, text: "الَّذِي خَلَقَ الْمَوْتَ وَالْحَيَاةَ لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا ۚ وَهُوَ الْعَزِيزُ الْغَفُورُ" },
      { number: 3, text: "الَّذِي خَلَقَ سَبْعَ سَمَاوَاتٍ طِبَاقًا ۖ مَّا تَرَىٰ فِي خَلْقِ الرَّحْمَٰنِ مِن تَفَاوُتٍ ۖ فَارْجِعِ الْبَصَرَ هَلْ تَرَىٰ مِن فُطُورٍ" },
    ],
  },
  {
    number: 68,
    nameArabic: "الْقَلَم",
    nameTranslit: "Al-Qalam",
    nameFr: "Le Calame",
    versesCount: 52,
    verses: [
      { number: 1, text: "نٓ ۚ وَالْقَلَمِ وَمَا يَسْطُرُونَ" },
    ],
  },
  {
    number: 69,
    nameArabic: "الْحَاقَّة",
    nameTranslit: "Al-Haqqa",
    nameFr: "La Vérité Inévitable",
    versesCount: 52,
    verses: [
      { number: 1, text: "الْحَاقَّةُ" },
      { number: 2, text: "مَا الْحَاقَّةُ" },
      { number: 3, text: "وَمَا أَدْرَاكَ مَا الْحَاقَّةُ" },
    ],
  },
  {
    number: 70,
    nameArabic: "الْمَعَارِج",
    nameTranslit: "Al-Ma'arij",
    nameFr: "Les Voies d'Ascension",
    versesCount: 44,
    verses: [
      { number: 1, text: "سَأَلَ سَائِلٌ بِعَذَابٍ وَاقِعٍ" },
    ],
  },
  {
    number: 71,
    nameArabic: "نُوح",
    nameTranslit: "Nuh",
    nameFr: "Noé",
    versesCount: 28,
    verses: [
      { number: 1, text: "إِنَّا أَرْسَلْنَا نُوحًا إِلَىٰ قَوْمِهِ أَنْ أَنذِرْ قَوْمَكَ مِن قَبْلِ أَن يَأْتِيَهُمْ عَذَابٌ أَلِيمٌ" },
    ],
  },
  {
    number: 72,
    nameArabic: "الْجِن",
    nameTranslit: "Al-Jinn",
    nameFr: "Les Djinns",
    versesCount: 28,
    verses: [
      { number: 1, text: "قُلْ أُوحِيَ إِلَيَّ أَنَّهُ اسْتَمَعَ نَفَرٌ مِّنَ الْجِنِّ فَقَالُوا إِنَّا سَمِعْنَا قُرْآنًا عَجَبًا" },
    ],
  },
  {
    number: 73,
    nameArabic: "الْمُزَّمِّل",
    nameTranslit: "Al-Muzzammil",
    nameFr: "L'Enveloppé",
    versesCount: 20,
    verses: [
      { number: 1, text: "يَا أَيُّهَا الْمُزَّمِّلُ" },
      { number: 2, text: "قُمِ اللَّيْلَ إِلَّا قَلِيلًا" },
      { number: 3, text: "نِّصْفَهُ أَوِ انقُصْ مِنْهُ قَلِيلًا" },
      { number: 4, text: "أَوْ زِدْ عَلَيْهِ وَرَتِّلِ الْقُرْآنَ تَرْتِيلًا" },
    ],
  },
  {
    number: 74,
    nameArabic: "الْمُدَّثِّر",
    nameTranslit: "Al-Muddaththir",
    nameFr: "Le Revêtu d'un Manteau",
    versesCount: 56,
    verses: [
      { number: 1, text: "يَا أَيُّهَا الْمُدَّثِّرُ" },
      { number: 2, text: "قُمْ فَأَنذِرْ" },
      { number: 3, text: "وَرَبَّكَ فَكَبِّرْ" },
      { number: 4, text: "وَثِيَابَكَ فَطَهِّرْ" },
      { number: 5, text: "وَالرُّجْزَ فَاهْجُرْ" },
    ],
  },
  {
    number: 75,
    nameArabic: "الْقِيَامَة",
    nameTranslit: "Al-Qiyama",
    nameFr: "La Résurrection",
    versesCount: 40,
    verses: [
      { number: 1, text: "لَا أُقْسِمُ بِيَوْمِ الْقِيَامَةِ" },
      { number: 2, text: "وَلَا أُقْسِمُ بِالنَّفْسِ اللَّوَّامَةِ" },
    ],
  },
  {
    number: 76,
    nameArabic: "الْإِنسَان",
    nameTranslit: "Al-Insan",
    nameFr: "L'Homme",
    versesCount: 31,
    verses: [
      { number: 1, text: "هَلْ أَتَىٰ عَلَى الْإِنسَانِ حِينٌ مِّنَ الدَّهْرِ لَمْ يَكُن شَيْئًا مَّذْكُورًا" },
    ],
  },
  {
    number: 77,
    nameArabic: "الْمُرْسَلَات",
    nameTranslit: "Al-Mursalat",
    nameFr: "Les Envoyés",
    versesCount: 50,
    verses: [
      { number: 1, text: "وَالْمُرْسَلَاتِ عُرْفًا" },
      { number: 2, text: "فَالْعَاصِفَاتِ عَصْفًا" },
    ],
  },
  {
    number: 78,
    nameArabic: "النَّبَإ",
    nameTranslit: "An-Naba",
    nameFr: "La Nouvelle",
    versesCount: 40,
    verses: [
      { number: 1, text: "عَمَّ يَتَسَاءَلُونَ" },
      { number: 2, text: "عَنِ النَّبَإِ الْعَظِيمِ" },
      { number: 3, text: "الَّذِي هُمْ فِيهِ مُخْتَلِفُونَ" },
      { number: 4, text: "كَلَّا سَيَعْلَمُونَ" },
      { number: 5, text: "ثُمَّ كَلَّا سَيَعْلَمُونَ" },
      { number: 6, text: "أَلَمْ نَجْعَلِ الْأَرْضَ مِهَادًا" },
      { number: 7, text: "وَالْجِبَالَ أَوْتَادًا" },
      { number: 8, text: "وَخَلَقْنَاكُمْ أَزْوَاجًا" },
      { number: 9, text: "وَجَعَلْنَا نَوْمَكُمْ سُبَاتًا" },
      { number: 10, text: "وَجَعَلْنَا اللَّيْلَ لِبَاسًا" },
      { number: 11, text: "وَجَعَلْنَا النَّهَارَ مَعَاشًا" },
      { number: 12, text: "وَبَنَيْنَا فَوْقَكُمْ سَبْعًا شِدَادًا" },
      { number: 13, text: "وَجَعَلْنَا سِرَاجًا وَهَّاجًا" },
      { number: 14, text: "وَأَنزَلْنَا مِنَ الْمُعْصِرَاتِ مَاءً ثَجَّاجًا" },
      { number: 15, text: "لِّنُخْرِجَ بِهِ حَبًّا وَنَبَاتًا" },
      { number: 16, text: "وَجَنَّاتٍ أَلْفَافًا" },
      { number: 17, text: "إِنَّ يَوْمَ الْفَصْلِ كَانَ مِيقَاتًا" },
      { number: 18, text: "يَوْمَ يُنفَخُ فِي الصُّورِ فَتَأْتُونَ أَفْوَاجًا" },
      { number: 19, text: "وَفُتِحَتِ السَّمَاءُ فَكَانَتْ أَبْوَابًا" },
      { number: 20, text: "وَسُيِّرَتِ الْجِبَالُ فَكَانَتْ سَرَابًا" },
      { number: 21, text: "إِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًا" },
      { number: 22, text: "لِّلطَّاغِينَ مَآبًا" },
      { number: 23, text: "لَّابِثِينَ فِيهَا أَحْقَابًا" },
      { number: 24, text: "لَّا يَذُوقُونَ فِيهَا بَرْدًا وَلَا شَرَابًا" },
      { number: 25, text: "إِلَّا حَمِيمًا وَغَسَّاقًا" },
      { number: 26, text: "جَزَاءً وِفَاقًا" },
      { number: 27, text: "إِنَّهُمْ كَانُوا لَا يَرْجُونَ حِسَابًا" },
      { number: 28, text: "وَكَذَّبُوا بِآيَاتِنَا كِذَّابًا" },
      { number: 29, text: "وَكُلَّ شَيْءٍ أَحْصَيْنَاهُ كِتَابًا" },
      { number: 30, text: "فَذُوقُوا فَلَن نَّزِيدَكُمْ إِلَّا عَذَابًا" },
      { number: 31, text: "إِنَّ لِلْمُتَّقِينَ مَفَازًا" },
      { number: 32, text: "حَدَائِقَ وَأَعْنَابًا" },
      { number: 33, text: "وَكَوَاعِبَ أَتْرَابًا" },
      { number: 34, text: "وَكَأْسًا دِهَاقًا" },
      { number: 35, text: "لَّا يَسْمَعُونَ فِيهَا لَغْوًا وَلَا كِذَّابًا" },
      { number: 36, text: "جَزَاءً مِّن رَّبِّكَ عَطَاءً حِسَابًا" },
      { number: 37, text: "رَّبِّ السَّمَاوَاتِ وَالْأَرْضِ وَمَا بَيْنَهُمَا الرَّحْمَٰنِ ۖ لَا يَمْلِكُونَ مِنْهُ خِطَابًا" },
      { number: 38, text: "يَوْمَ يَقُومُ الرُّوحُ وَالْمَلَائِكَةُ صَفًّا ۖ لَّا يَتَكَلَّمُونَ إِلَّا مَنْ أَذِنَ لَهُ الرَّحْمَٰنُ وَقَالَ صَوَابًا" },
      { number: 39, text: "ذَٰلِكَ الْيَوْمُ الْحَقُّ ۖ فَمَن شَاءَ اتَّخَذَ إِلَىٰ رَبِّهِ مَآبًا" },
      { number: 40, text: "إِنَّا أَنذَرْنَاكُمْ عَذَابًا قَرِيبًا يَوْمَ يَنظُرُ الْمَرْءُ مَا قَدَّمَتْ يَدَاهُ وَيَقُولُ الْكَافِرُ يَا لَيْتَنِي كُنتُ تُرَابًا" },
    ],
  },
  {
    number: 79,
    nameArabic: "النَّازِعَات",
    nameTranslit: "An-Nazi'at",
    nameFr: "Ceux qui Arrachent",
    versesCount: 46,
    verses: [
      { number: 1, text: "وَالنَّازِعَاتِ غَرْقًا" },
      { number: 2, text: "وَالنَّاشِطَاتِ نَشْطًا" },
      { number: 3, text: "وَالسَّابِحَاتِ سَبْحًا" },
      { number: 4, text: "فَالسَّابِقَاتِ سَبْقًا" },
      { number: 5, text: "فَالْمُدَبِّرَاتِ أَمْرًا" },
      { number: 6, text: "يَوْمَ تَرْجُفُ الرَّاجِفَةُ" },
      { number: 7, text: "تَتْبَعُهَا الرَّادِفَةُ" },
      { number: 27, text: "أَأَنتُمْ أَشَدُّ خَلْقًا أَمِ السَّمَاءُ ۚ بَنَاهَا" },
      { number: 28, text: "رَفَعَ سَمْكَهَا فَسَوَّاهَا" },
      { number: 46, text: "كَأَنَّهُمْ يَوْمَ يَرَوْنَهَا لَمْ يَلْبَثُوا إِلَّا عَشِيَّةً أَوْ ضُحَاهَا" },
    ],
  },
  {
    number: 80,
    nameArabic: "عَبَسَ",
    nameTranslit: "'Abasa",
    nameFr: "Il S'est Renfrogné",
    versesCount: 42,
    verses: [
      { number: 1, text: "عَبَسَ وَتَوَلَّىٰ" },
      { number: 2, text: "أَن جَاءَهُ الْأَعْمَىٰ" },
      { number: 3, text: "وَمَا يُدْرِيكَ لَعَلَّهُ يَزَّكَّىٰ" },
      { number: 4, text: "أَوْ يَذَّكَّرُ فَتَنفَعَهُ الذِّكْرَىٰ" },
      { number: 33, text: "فَإِذَا جَاءَتِ الصَّاخَّةُ" },
      { number: 34, text: "يَوْمَ يَفِرُّ الْمَرْءُ مِنْ أَخِيهِ" },
      { number: 35, text: "وَأُمِّهِ وَأَبِيهِ" },
      { number: 36, text: "وَصَاحِبَتِهِ وَبَنِيهِ" },
      { number: 37, text: "لِكُلِّ امْرِئٍ مِّنْهُمْ يَوْمَئِذٍ شَأْنٌ يُغْنِيهِ" },
    ],
  },
  {
    number: 81,
    nameArabic: "التَّكْوِير",
    nameTranslit: "At-Takwir",
    nameFr: "L'Enroulement",
    versesCount: 29,
    verses: [
      { number: 1, text: "إِذَا الشَّمْسُ كُوِّرَتْ" },
      { number: 2, text: "وَإِذَا النُّجُومُ انكَدَرَتْ" },
      { number: 3, text: "وَإِذَا الْجِبَالُ سُيِّرَتْ" },
      { number: 4, text: "وَإِذَا الْعِشَارُ عُطِّلَتْ" },
      { number: 5, text: "وَإِذَا الْوُحُوشُ حُشِرَتْ" },
      { number: 6, text: "وَإِذَا الْبِحَارُ سُجِّرَتْ" },
      { number: 7, text: "وَإِذَا النُّفُوسُ زُوِّجَتْ" },
      { number: 8, text: "وَإِذَا الْمَوْءُودَةُ سُئِلَتْ" },
      { number: 9, text: "بِأَيِّ ذَنبٍ قُتِلَتْ" },
      { number: 10, text: "وَإِذَا الصُّحُفُ نُشِرَتْ" },
      { number: 11, text: "وَإِذَا السَّمَاءُ كُشِطَتْ" },
      { number: 12, text: "وَإِذَا الْجَحِيمُ سُعِّرَتْ" },
      { number: 13, text: "وَإِذَا الْجَنَّةُ أُزْلِفَتْ" },
      { number: 14, text: "عَلِمَتْ نَفْسٌ مَّا أَحْضَرَتْ" },
      { number: 15, text: "فَلَا أُقْسِمُ بِالْخُنَّسِ" },
      { number: 16, text: "الْجَوَارِ الْكُنَّسِ" },
      { number: 17, text: "وَاللَّيْلِ إِذَا عَسْعَسَ" },
      { number: 18, text: "وَالصُّبْحِ إِذَا تَنَفَّسَ" },
      { number: 19, text: "إِنَّهُ لَقَوْلُ رَسُولٍ كَرِيمٍ" },
      { number: 20, text: "ذِي قُوَّةٍ عِندَ ذِي الْعَرْشِ مَكِينٍ" },
      { number: 21, text: "مُّطَاعٍ ثَمَّ أَمِينٍ" },
      { number: 22, text: "وَمَا صَاحِبُكُم بِمَجْنُونٍ" },
      { number: 23, text: "وَلَقَدْ رَآهُ بِالْأُفُقِ الْمُبِينِ" },
      { number: 24, text: "وَمَا هُوَ عَلَى الْغَيْبِ بِضَنِينٍ" },
      { number: 25, text: "وَمَا هُوَ بِقَوْلِ شَيْطَانٍ رَّجِيمٍ" },
      { number: 26, text: "فَأَيْنَ تَذْهَبُونَ" },
      { number: 27, text: "إِنْ هُوَ إِلَّا ذِكْرٌ لِّلْعَالَمِينَ" },
      { number: 28, text: "لِمَن شَاءَ مِنكُمْ أَن يَسْتَقِيمَ" },
      { number: 29, text: "وَمَا تَشَاءُونَ إِلَّا أَن يَشَاءَ اللَّهُ رَبُّ الْعَالَمِينَ" },
    ],
  },
  {
    number: 82,
    nameArabic: "الْإِنفِطَار",
    nameTranslit: "Al-Infitar",
    nameFr: "La Déchirure",
    versesCount: 19,
    verses: [
      { number: 1, text: "إِذَا السَّمَاءُ انفَطَرَتْ" },
      { number: 2, text: "وَإِذَا الْكَوَاكِبُ انتَثَرَتْ" },
      { number: 3, text: "وَإِذَا الْبِحَارُ فُجِّرَتْ" },
      { number: 4, text: "وَإِذَا الْقُبُورُ بُعْثِرَتْ" },
      { number: 5, text: "عَلِمَتْ نَفْسٌ مَّا قَدَّمَتْ وَأَخَّرَتْ" },
      { number: 6, text: "يَا أَيُّهَا الْإِنسَانُ مَا غَرَّكَ بِرَبِّكَ الْكَرِيمِ" },
      { number: 7, text: "الَّذِي خَلَقَكَ فَسَوَّاكَ فَعَدَلَكَ" },
      { number: 8, text: "فِي أَيِّ صُورَةٍ مَّا شَاءَ رَكَّبَكَ" },
      { number: 9, text: "كَلَّا بَلْ تُكَذِّبُونَ بِالدِّينِ" },
      { number: 10, text: "وَإِنَّ عَلَيْكُمْ لَحَافِظِينَ" },
      { number: 11, text: "كِرَامًا كَاتِبِينَ" },
      { number: 12, text: "يَعْلَمُونَ مَا تَفْعَلُونَ" },
      { number: 13, text: "إِنَّ الْأَبْرَارَ لَفِي نَعِيمٍ" },
      { number: 14, text: "وَإِنَّ الْفُجَّارَ لَفِي جَحِيمٍ" },
      { number: 15, text: "يَصْلَوْنَهَا يَوْمَ الدِّينِ" },
      { number: 16, text: "وَمَا هُمْ عَنْهَا بِغَائِبِينَ" },
      { number: 17, text: "وَمَا أَدْرَاكَ مَا يَوْمُ الدِّينِ" },
      { number: 18, text: "ثُمَّ مَا أَدْرَاكَ مَا يَوْمُ الدِّينِ" },
      { number: 19, text: "يَوْمَ لَا تَمْلِكُ نَفْسٌ لِّنَفْسٍ شَيْئًا ۖ وَالْأَمْرُ يَوْمَئِذٍ لِّلَّهِ" },
    ],
  },
  {
    number: 83,
    nameArabic: "الْمُطَفِّفِين",
    nameTranslit: "Al-Mutaffifin",
    nameFr: "Les Fraudeurs",
    versesCount: 36,
    verses: [
      { number: 1, text: "وَيْلٌ لِّلْمُطَفِّفِينَ" },
      { number: 2, text: "الَّذِينَ إِذَا اكْتَالُوا عَلَى النَّاسِ يَسْتَوْفُونَ" },
      { number: 3, text: "وَإِذَا كَالُوهُمْ أَو وَّزَنُوهُمْ يُخْسِرُونَ" },
      { number: 4, text: "أَلَا يَظُنُّ أُولَٰئِكَ أَنَّهُم مَّبْعُوثُونَ" },
      { number: 5, text: "لِيَوْمٍ عَظِيمٍ" },
      { number: 22, text: "عَلَى الْأَرَائِكِ يَنظُرُونَ" },
      { number: 23, text: "تَعْرِفُ فِي وُجُوهِهِمْ نَضْرَةَ النَّعِيمِ" },
      { number: 24, text: "يُسْقَوْنَ مِن رَّحِيقٍ مَّخْتُومٍ" },
      { number: 25, text: "خِتَامُهُ مِسْكٌ ۚ وَفِي ذَٰلِكَ فَلْيَتَنَافَسِ الْمُتَنَافِسُونَ" },
      { number: 26, text: "وَمِزَاجُهُ مِن تَسْنِيمٍ" },
    ],
  },
  {
    number: 84,
    nameArabic: "الْإِنشِقَاق",
    nameTranslit: "Al-Inshiqaq",
    nameFr: "La Déchirure",
    versesCount: 25,
    verses: [
      { number: 1, text: "إِذَا السَّمَاءُ انشَقَّتْ" },
      { number: 2, text: "وَأَذِنَتْ لِرَبِّهَا وَحُقَّتْ" },
      { number: 3, text: "وَإِذَا الْأَرْضُ مُدَّتْ" },
      { number: 4, text: "وَأَلْقَتْ مَا فِيهَا وَتَخَلَّتْ" },
      { number: 5, text: "وَأَذِنَتْ لِرَبِّهَا وَحُقَّتْ" },
      { number: 6, text: "يَا أَيُّهَا الْإِنسَانُ إِنَّكَ كَادِحٌ إِلَىٰ رَبِّكَ كَدْحًا فَمُلَاقِيهِ" },
    ],
  },
  {
    number: 85,
    nameArabic: "الْبُرُوج",
    nameTranslit: "Al-Buruj",
    nameFr: "Les Constellations",
    versesCount: 22,
    verses: [
      { number: 1, text: "وَالسَّمَاءِ ذَاتِ الْبُرُوجِ" },
      { number: 2, text: "وَالْيَوْمِ الْمَوْعُودِ" },
      { number: 3, text: "وَشَاهِدٍ وَمَشْهُودٍ" },
      { number: 4, text: "قُتِلَ أَصْحَابُ الْأُخْدُودِ" },
      { number: 5, text: "النَّارِ ذَاتِ الْوَقُودِ" },
      { number: 11, text: "إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ لَهُمْ جَنَّاتٌ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ ۚ ذَٰلِكَ الْفَوْزُ الْكَبِيرُ" },
      { number: 21, text: "بَلْ هُوَ قُرْآنٌ مَّجِيدٌ" },
      { number: 22, text: "فِي لَوْحٍ مَّحْفُوظٍ" },
    ],
  },
  {
    number: 86,
    nameArabic: "الطَّارِق",
    nameTranslit: "At-Tariq",
    nameFr: "L'Astre Nocturne",
    versesCount: 17,
    verses: [
      { number: 1, text: "وَالسَّمَاءِ وَالطَّارِقِ" },
      { number: 2, text: "وَمَا أَدْرَاكَ مَا الطَّارِقُ" },
      { number: 3, text: "النَّجْمُ الثَّاقِبُ" },
      { number: 4, text: "إِن كُلُّ نَفْسٍ لَّمَّا عَلَيْهَا حَافِظٌ" },
      { number: 11, text: "وَالسَّمَاءِ ذَاتِ الرَّجْعِ" },
      { number: 12, text: "وَالْأَرْضِ ذَاتِ الصَّدْعِ" },
      { number: 13, text: "إِنَّهُ لَقَوْلٌ فَصْلٌ" },
      { number: 14, text: "وَمَا هُوَ بِالْهَزْلِ" },
    ],
  },
  {
    number: 87,
    nameArabic: "الْأَعْلَى",
    nameTranslit: "Al-A'la",
    nameFr: "Le Très-Haut",
    versesCount: 19,
    verses: [
      { number: 1, text: "سَبِّحِ اسْمَ رَبِّكَ الْأَعْلَى" },
      { number: 2, text: "الَّذِي خَلَقَ فَسَوَّىٰ" },
      { number: 3, text: "وَالَّذِي قَدَّرَ فَهَدَىٰ" },
      { number: 4, text: "وَالَّذِي أَخْرَجَ الْمَرْعَىٰ" },
      { number: 5, text: "فَجَعَلَهُ غُثَاءً أَحْوَىٰ" },
      { number: 6, text: "سَنُقْرِئُكَ فَلَا تَنسَىٰ" },
      { number: 7, text: "إِلَّا مَا شَاءَ اللَّهُ ۚ إِنَّهُ يَعْلَمُ الْجَهْرَ وَمَا يَخْفَىٰ" },
      { number: 8, text: "وَنُيَسِّرُكَ لِلْيُسْرَىٰ" },
      { number: 9, text: "فَذَكِّرْ إِن نَّفَعَتِ الذِّكْرَىٰ" },
      { number: 10, text: "سَيَذَّكَّرُ مَن يَخْشَىٰ" },
      { number: 11, text: "وَيَتَجَنَّبُهَا الْأَشْقَى" },
      { number: 12, text: "الَّذِي يَصْلَى النَّارَ الْكُبْرَىٰ" },
      { number: 13, text: "ثُمَّ لَا يَمُوتُ فِيهَا وَلَا يَحْيَىٰ" },
      { number: 14, text: "قَدْ أَفْلَحَ مَن تَزَكَّىٰ" },
      { number: 15, text: "وَذَكَرَ اسْمَ رَبِّهِ فَصَلَّىٰ" },
      { number: 16, text: "بَلْ تُؤْثِرُونَ الْحَيَاةَ الدُّنْيَا" },
      { number: 17, text: "وَالْآخِرَةُ خَيْرٌ وَأَبْقَىٰ" },
      { number: 18, text: "إِنَّ هَٰذَا لَفِي الصُّحُفِ الْأُولَىٰ" },
      { number: 19, text: "صُحُفِ إِبْرَاهِيمَ وَمُوسَىٰ" },
    ],
  },
  {
    number: 88,
    nameArabic: "الْغَاشِيَة",
    nameTranslit: "Al-Ghashiya",
    nameFr: "L'Enveloppant",
    versesCount: 26,
    verses: [
      { number: 1, text: "هَلْ أَتَاكَ حَدِيثُ الْغَاشِيَةِ" },
      { number: 2, text: "وُجُوهٌ يَوْمَئِذٍ خَاشِعَةٌ" },
      { number: 3, text: "عَامِلَةٌ نَّاصِبَةٌ" },
      { number: 4, text: "تَصْلَىٰ نَارًا حَامِيَةً" },
      { number: 5, text: "تُسْقَىٰ مِنْ عَيْنٍ آنِيَةٍ" },
      { number: 8, text: "وُجُوهٌ يَوْمَئِذٍ نَّاعِمَةٌ" },
      { number: 9, text: "لِّسَعْيِهَا رَاضِيَةٌ" },
      { number: 17, text: "أَفَلَا يَنظُرُونَ إِلَى الْإِبِلِ كَيْفَ خُلِقَتْ" },
      { number: 18, text: "وَإِلَى السَّمَاءِ كَيْفَ رُفِعَتْ" },
      { number: 19, text: "وَإِلَى الْجِبَالِ كَيْفَ نُصِبَتْ" },
      { number: 20, text: "وَإِلَى الْأَرْضِ كَيْفَ سُطِحَتْ" },
      { number: 21, text: "فَذَكِّرْ إِنَّمَا أَنتَ مُذَكِّرٌ" },
      { number: 22, text: "لَّسْتَ عَلَيْهِم بِمُصَيْطِرٍ" },
    ],
  },
  {
    number: 89,
    nameArabic: "الْفَجْر",
    nameTranslit: "Al-Fajr",
    nameFr: "L'Aube",
    versesCount: 30,
    verses: [
      { number: 1, text: "وَالْفَجْرِ" },
      { number: 2, text: "وَلَيَالٍ عَشْرٍ" },
      { number: 3, text: "وَالشَّفْعِ وَالْوَتْرِ" },
      { number: 4, text: "وَاللَّيْلِ إِذَا يَسْرِ" },
      { number: 27, text: "يَا أَيَّتُهَا النَّفْسُ الْمُطْمَئِنَّةُ" },
      { number: 28, text: "ارْجِعِي إِلَىٰ رَبِّكِ رَاضِيَةً مَّرْضِيَّةً" },
      { number: 29, text: "فَادْخُلِي فِي عِبَادِي" },
      { number: 30, text: "وَادْخُلِي جَنَّتِي" },
    ],
  },
  {
    number: 90,
    nameArabic: "الْبَلَد",
    nameTranslit: "Al-Balad",
    nameFr: "La Cité",
    versesCount: 20,
    verses: [
      { number: 1, text: "لَا أُقْسِمُ بِهَٰذَا الْبَلَدِ" },
      { number: 2, text: "وَأَنتَ حِلٌّ بِهَٰذَا الْبَلَدِ" },
      { number: 3, text: "وَوَالِدٍ وَمَا وَلَدَ" },
      { number: 4, text: "لَقَدْ خَلَقْنَا الْإِنسَانَ فِي كَبَدٍ" },
      { number: 12, text: "وَمَا أَدْرَاكَ مَا الْعَقَبَةُ" },
      { number: 13, text: "فَكُّ رَقَبَةٍ" },
      { number: 14, text: "أَوْ إِطْعَامٌ فِي يَوْمٍ ذِي مَسْغَبَةٍ" },
      { number: 15, text: "يَتِيمًا ذَا مَقْرَبَةٍ" },
      { number: 16, text: "أَوْ مِسْكِينًا ذَا مَتْرَبَةٍ" },
      { number: 17, text: "ثُمَّ كَانَ مِنَ الَّذِينَ آمَنُوا وَتَوَاصَوْا بِالصَّبْرِ وَتَوَاصَوْا بِالْمَرْحَمَةِ" },
    ],
  },
  {
    number: 91,
    nameArabic: "الشَّمْس",
    nameTranslit: "Ash-Shams",
    nameFr: "Le Soleil",
    versesCount: 15,
    verses: [
      { number: 1, text: "وَالشَّمْسِ وَضُحَاهَا" },
      { number: 2, text: "وَالْقَمَرِ إِذَا تَلَاهَا" },
      { number: 3, text: "وَالنَّهَارِ إِذَا جَلَّاهَا" },
      { number: 4, text: "وَاللَّيْلِ إِذَا يَغْشَاهَا" },
      { number: 5, text: "وَالسَّمَاءِ وَمَا بَنَاهَا" },
      { number: 6, text: "وَالْأَرْضِ وَمَا طَحَاهَا" },
      { number: 7, text: "وَنَفْسٍ وَمَا سَوَّاهَا" },
      { number: 8, text: "فَأَلْهَمَهَا فُجُورَهَا وَتَقْوَاهَا" },
      { number: 9, text: "قَدْ أَفْلَحَ مَن زَكَّاهَا" },
      { number: 10, text: "وَقَدْ خَابَ مَن دَسَّاهَا" },
      { number: 11, text: "كَذَّبَتْ ثَمُودُ بِطَغْوَاهَا" },
      { number: 14, text: "فَكَذَّبُوهُ فَعَقَرُوهَا فَدَمْدَمَ عَلَيْهِمْ رَبُّهُم بِذَنبِهِمْ فَسَوَّاهَا" },
      { number: 15, text: "وَلَا يَخَافُ عُقْبَاهَا" },
    ],
  },
  {
    number: 92,
    nameArabic: "اللَّيْل",
    nameTranslit: "Al-Layl",
    nameFr: "La Nuit",
    versesCount: 21,
    verses: [
      { number: 1, text: "وَاللَّيْلِ إِذَا يَغْشَىٰ" },
      { number: 2, text: "وَالنَّهَارِ إِذَا تَجَلَّىٰ" },
      { number: 3, text: "وَمَا خَلَقَ الذَّكَرَ وَالْأُنثَىٰ" },
      { number: 4, text: "إِنَّ سَعْيَكُمْ لَشَتَّىٰ" },
      { number: 5, text: "فَأَمَّا مَنْ أَعْطَىٰ وَاتَّقَىٰ" },
      { number: 6, text: "وَصَدَّقَ بِالْحُسْنَىٰ" },
      { number: 7, text: "فَسَنُيَسِّرُهُ لِلْيُسْرَىٰ" },
      { number: 17, text: "وَسَيُجَنَّبُهَا الْأَتْقَى" },
      { number: 18, text: "الَّذِي يُؤْتِي مَالَهُ يَتَزَكَّىٰ" },
      { number: 19, text: "وَمَا لِأَحَدٍ عِندَهُ مِن نِّعْمَةٍ تُجْزَىٰ" },
      { number: 20, text: "إِلَّا ابْتِغَاءَ وَجْهِ رَبِّهِ الْأَعْلَىٰ" },
      { number: 21, text: "وَلَسَوْفَ يَرْضَىٰ" },
    ],
  },
  {
    number: 93,
    nameArabic: "الضُّحَى",
    nameTranslit: "Ad-Duha",
    nameFr: "La Matinée",
    versesCount: 11,
    verses: [
      { number: 1, text: "وَالضُّحَىٰ" },
      { number: 2, text: "وَاللَّيْلِ إِذَا سَجَىٰ" },
      { number: 3, text: "مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ" },
      { number: 4, text: "وَلَلْآخِرَةُ خَيْرٌ لَّكَ مِنَ الْأُولَىٰ" },
      { number: 5, text: "وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ" },
      { number: 6, text: "أَلَمْ يَجِدْكَ يَتِيمًا فَآوَىٰ" },
      { number: 7, text: "وَوَجَدَكَ ضَالًّا فَهَدَىٰ" },
      { number: 8, text: "وَوَجَدَكَ عَائِلًا فَأَغْنَىٰ" },
      { number: 9, text: "فَأَمَّا الْيَتِيمَ فَلَا تَقْهَرْ" },
      { number: 10, text: "وَأَمَّا السَّائِلَ فَلَا تَنْهَرْ" },
      { number: 11, text: "وَأَمَّا بِنِعْمَةِ رَبِّكَ فَحَدِّثْ" },
    ],
  },
  {
    number: 94,
    nameArabic: "الشَّرْح",
    nameTranslit: "Ash-Sharh",
    nameFr: "L'Ouverture de la Poitrine",
    versesCount: 8,
    verses: [
      { number: 1, text: "أَلَمْ نَشْرَحْ لَكَ صَدْرَكَ" },
      { number: 2, text: "وَوَضَعْنَا عَنكَ وِزْرَكَ" },
      { number: 3, text: "الَّذِي أَنقَضَ ظَهْرَكَ" },
      { number: 4, text: "وَرَفَعْنَا لَكَ ذِكْرَكَ" },
      { number: 5, text: "فَإِنَّ مَعَ الْعُسْرِ يُسْرًا" },
      { number: 6, text: "إِنَّ مَعَ الْعُسْرِ يُسْرًا" },
      { number: 7, text: "فَإِذَا فَرَغْتَ فَانصَبْ" },
      { number: 8, text: "وَإِلَىٰ رَبِّكَ فَارْغَبْ" },
    ],
  },
  {
    number: 95,
    nameArabic: "التِّين",
    nameTranslit: "At-Tin",
    nameFr: "Le Figuier",
    versesCount: 8,
    verses: [
      { number: 1, text: "وَالتِّينِ وَالزَّيْتُونِ" },
      { number: 2, text: "وَطُورِ سِينِينَ" },
      { number: 3, text: "وَهَٰذَا الْبَلَدِ الْأَمِينِ" },
      { number: 4, text: "لَقَدْ خَلَقْنَا الْإِنسَانَ فِي أَحْسَنِ تَقْوِيمٍ" },
      { number: 5, text: "ثُمَّ رَدَدْنَاهُ أَسْفَلَ سَافِلِينَ" },
      { number: 6, text: "إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ فَلَهُمْ أَجْرٌ غَيْرُ مَمْنُونٍ" },
      { number: 7, text: "فَمَا يُكَذِّبُكَ بَعْدُ بِالدِّينِ" },
      { number: 8, text: "أَلَيْسَ اللَّهُ بِأَحْكَمِ الْحَاكِمِينَ" },
    ],
  },
  {
    number: 96,
    nameArabic: "الْعَلَق",
    nameTranslit: "Al-Alaq",
    nameFr: "La Adhérence",
    versesCount: 19,
    verses: [
      { number: 1, text: "اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ" },
      { number: 2, text: "خَلَقَ الْإِنسَانَ مِنْ عَلَقٍ" },
      { number: 3, text: "اقْرَأْ وَرَبُّكَ الْأَكْرَمُ" },
      { number: 4, text: "الَّذِي عَلَّمَ بِالْقَلَمِ" },
      { number: 5, text: "عَلَّمَ الْإِنسَانَ مَا لَمْ يَعْلَمْ" },
      { number: 6, text: "كَلَّا إِنَّ الْإِنسَانَ لَيَطْغَى" },
      { number: 7, text: "أَن رَّآهُ اسْتَغْنَىٰ" },
      { number: 19, text: "كَلَّا لَا تُطِعْهُ وَاسْجُدْ وَاقْتَرِب" },
    ],
  },
  {
    number: 97,
    nameArabic: "الْقَدْر",
    nameTranslit: "Al-Qadr",
    nameFr: "La Nuit du Destin",
    versesCount: 5,
    verses: [
      { number: 1, text: "إِنَّا أَنزَلْنَاهُ فِي لَيْلَةِ الْقَدْرِ" },
      { number: 2, text: "وَمَا أَدْرَاكَ مَا لَيْلَةُ الْقَدْرِ" },
      { number: 3, text: "لَيْلَةُ الْقَدْرِ خَيْرٌ مِّنْ أَلْفِ شَهْرٍ" },
      { number: 4, text: "تَنَزَّلُ الْمَلَائِكَةُ وَالرُّوحُ فِيهَا بِإِذْنِ رَبِّهِم مِّن كُلِّ أَمْرٍ" },
      { number: 5, text: "سَلَامٌ هِيَ حَتَّىٰ مَطْلَعِ الْفَجْرِ" },
    ],
  },
  {
    number: 98,
    nameArabic: "الْبَيِّنَة",
    nameTranslit: "Al-Bayyina",
    nameFr: "La Preuve",
    versesCount: 8,
    verses: [
      { number: 1, text: "لَمْ يَكُنِ الَّذِينَ كَفَرُوا مِنْ أَهْلِ الْكِتَابِ وَالْمُشْرِكِينَ مُنفَكِّينَ حَتَّىٰ تَأْتِيَهُمُ الْبَيِّنَةُ" },
      { number: 5, text: "وَمَا أُمِرُوا إِلَّا لِيَعْبُدُوا اللَّهَ مُخْلِصِينَ لَهُ الدِّينَ حُنَفَاءَ وَيُقِيمُوا الصَّلَاةَ وَيُؤْتُوا الزَّكَاةَ ۚ وَذَٰلِكَ دِينُ الْقَيِّمَةِ" },
      { number: 7, text: "إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ أُولَٰئِكَ هُمْ خَيْرُ الْبَرِيَّةِ" },
      { number: 8, text: "جَزَاؤُهُمْ عِندَ رَبِّهِمْ جَنَّاتُ عَدْنٍ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ خَالِدِينَ فِيهَا أَبَدًا ۖ رَّضِيَ اللَّهُ عَنْهُمْ وَرَضُوا عَنْهُ ۚ ذَٰلِكَ لِمَنْ خَشِيَ رَبَّهُ" },
    ],
  },
  {
    number: 99,
    nameArabic: "الزَّلْزَلَة",
    nameTranslit: "Az-Zalzala",
    nameFr: "Le Séisme",
    versesCount: 8,
    verses: [
      { number: 1, text: "إِذَا زُلْزِلَتِ الْأَرْضُ زِلْزَالَهَا" },
      { number: 2, text: "وَأَخْرَجَتِ الْأَرْضُ أَثْقَالَهَا" },
      { number: 3, text: "وَقَالَ الْإِنسَانُ مَا لَهَا" },
      { number: 4, text: "يَوْمَئِذٍ تُحَدِّثُ أَخْبَارَهَا" },
      { number: 5, text: "بِأَنَّ رَبَّكَ أَوْحَىٰ لَهَا" },
      { number: 6, text: "يَوْمَئِذٍ يَصْدُرُ النَّاسُ أَشْتَاتًا لِّيُرَوْا أَعْمَالَهُمْ" },
      { number: 7, text: "فَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ" },
      { number: 8, text: "وَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُ" },
    ],
  },
  {
    number: 100,
    nameArabic: "الْعَادِيَات",
    nameTranslit: "Al-Adiyat",
    nameFr: "Les Coursiers",
    versesCount: 11,
    verses: [
      { number: 1, text: "وَالْعَادِيَاتِ ضَبْحًا" },
      { number: 2, text: "فَالْمُورِيَاتِ قَدْحًا" },
      { number: 3, text: "فَالْمُغِيرَاتِ صُبْحًا" },
      { number: 4, text: "فَأَثَرْنَ بِهِ نَقْعًا" },
      { number: 5, text: "فَوَسَطْنَ بِهِ جَمْعًا" },
      { number: 6, text: "إِنَّ الْإِنسَانَ لِرَبِّهِ لَكَنُودٌ" },
      { number: 7, text: "وَإِنَّهُ عَلَىٰ ذَٰلِكَ لَشَهِيدٌ" },
      { number: 8, text: "وَإِنَّهُ لِحُبِّ الْخَيْرِ لَشَدِيدٌ" },
      { number: 9, text: "أَفَلَا يَعْلَمُ إِذَا بُعْثِرَ مَا فِي الْقُبُورِ" },
      { number: 10, text: "وَحُصِّلَ مَا فِي الصُّدُورِ" },
      { number: 11, text: "إِنَّ رَبَّهُم بِهِمْ يَوْمَئِذٍ لَّخَبِيرٌ" },
    ],
  },
  {
    number: 101,
    nameArabic: "الْقَارِعَة",
    nameTranslit: "Al-Qari'a",
    nameFr: "La Fracassante",
    versesCount: 11,
    verses: [
      { number: 1, text: "الْقَارِعَةُ" },
      { number: 2, text: "مَا الْقَارِعَةُ" },
      { number: 3, text: "وَمَا أَدْرَاكَ مَا الْقَارِعَةُ" },
      { number: 4, text: "يَوْمَ يَكُونُ النَّاسُ كَالْفَرَاشِ الْمَبْثُوثِ" },
      { number: 5, text: "وَتَكُونُ الْجِبَالُ كَالْعِهْنِ الْمَنفُوشِ" },
      { number: 6, text: "فَأَمَّا مَن ثَقُلَتْ مَوَازِينُهُ" },
      { number: 7, text: "فَهُوَ فِي عِيشَةٍ رَّاضِيَةٍ" },
      { number: 8, text: "وَأَمَّا مَنْ خَفَّتْ مَوَازِينُهُ" },
      { number: 9, text: "فَأُمُّهُ هَاوِيَةٌ" },
      { number: 10, text: "وَمَا أَدْرَاكَ مَا هِيَهْ" },
      { number: 11, text: "نَارٌ حَامِيَةٌ" },
    ],
  },
  {
    number: 102,
    nameArabic: "التَّكَاثُر",
    nameTranslit: "At-Takathur",
    nameFr: "La Rivalité",
    versesCount: 8,
    verses: [
      { number: 1, text: "أَلْهَاكُمُ التَّكَاثُرُ" },
      { number: 2, text: "حَتَّىٰ زُرْتُمُ الْمَقَابِرَ" },
      { number: 3, text: "كَلَّا سَوْفَ تَعْلَمُونَ" },
      { number: 4, text: "ثُمَّ كَلَّا سَوْفَ تَعْلَمُونَ" },
      { number: 5, text: "كَلَّا لَوْ تَعْلَمُونَ عِلْمَ الْيَقِينِ" },
      { number: 6, text: "لَتَرَوُنَّ الْجَحِيمَ" },
      { number: 7, text: "ثُمَّ لَتَرَوُنَّهَا عَيْنَ الْيَقِينِ" },
      { number: 8, text: "ثُمَّ لَتُسْأَلُنَّ يَوْمَئِذٍ عَنِ النَّعِيمِ" },
    ],
  },
  {
    number: 103,
    nameArabic: "الْعَصْر",
    nameTranslit: "Al-Asr",
    nameFr: "Le Temps",
    versesCount: 3,
    verses: [
      { number: 1, text: "وَالْعَصْرِ" },
      { number: 2, text: "إِنَّ الْإِنسَانَ لَفِي خُسْرٍ" },
      { number: 3, text: "إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ" },
    ],
  },
  {
    number: 104,
    nameArabic: "الْهُمَزَة",
    nameTranslit: "Al-Humaza",
    nameFr: "Le Diffamateur",
    versesCount: 9,
    verses: [
      { number: 1, text: "وَيْلٌ لِّكُلِّ هُمَزَةٍ لُّمَزَةٍ" },
      { number: 2, text: "الَّذِي جَمَعَ مَالًا وَعَدَّدَهُ" },
      { number: 3, text: "يَحْسَبُ أَنَّ مَالَهُ أَخْلَدَهُ" },
      { number: 4, text: "كَلَّا ۖ لَيُنبَذَنَّ فِي الْحُطَمَةِ" },
      { number: 5, text: "وَمَا أَدْرَاكَ مَا الْحُطَمَةُ" },
      { number: 6, text: "نَارُ اللَّهِ الْمُوقَدَةُ" },
      { number: 7, text: "الَّتِي تَطَّلِعُ عَلَى الْأَفْئِدَةِ" },
      { number: 8, text: "إِنَّهَا عَلَيْهِم مُّؤْصَدَةٌ" },
      { number: 9, text: "فِي عَمَدٍ مُّمَدَّدَةٍ" },
    ],
  },
  {
    number: 105,
    nameArabic: "الْفِيل",
    nameTranslit: "Al-Fil",
    nameFr: "L'Éléphant",
    versesCount: 5,
    verses: [
      { number: 1, text: "أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَابِ الْفِيلِ" },
      { number: 2, text: "أَلَمْ يَجْعَلْ كَيْدَهُمْ فِي تَضْلِيلٍ" },
      { number: 3, text: "وَأَرْسَلَ عَلَيْهِمْ طَيْرًا أَبَابِيلَ" },
      { number: 4, text: "تَرْمِيهِم بِحِجَارَةٍ مِّن سِجِّيلٍ" },
      { number: 5, text: "فَجَعَلَهُمْ كَعَصْفٍ مَّأْكُولٍ" },
    ],
  },
  {
    number: 106,
    nameArabic: "قُرَيْش",
    nameTranslit: "Quraysh",
    nameFr: "Quraish",
    versesCount: 4,
    verses: [
      { number: 1, text: "لِإِيلَافِ قُرَيْشٍ" },
      { number: 2, text: "إِيلَافِهِمْ رِحْلَةَ الشِّتَاءِ وَالصَّيْفِ" },
      { number: 3, text: "فَلْيَعْبُدُوا رَبَّ هَٰذَا الْبَيْتِ" },
      { number: 4, text: "الَّذِي أَطْعَمَهُم مِّن جُوعٍ وَآمَنَهُم مِّنْ خَوْفٍ" },
    ],
  },
  {
    number: 107,
    nameArabic: "الْمَاعُون",
    nameTranslit: "Al-Ma'un",
    nameFr: "L'Ustensile",
    versesCount: 7,
    verses: [
      { number: 1, text: "أَرَأَيْتَ الَّذِي يُكَذِّبُ بِالدِّينِ" },
      { number: 2, text: "فَذَٰلِكَ الَّذِي يَدُعُّ الْيَتِيمَ" },
      { number: 3, text: "وَلَا يَحُضُّ عَلَىٰ طَعَامِ الْمِسْكِينِ" },
      { number: 4, text: "فَوَيْلٌ لِّلْمُصَلِّينَ" },
      { number: 5, text: "الَّذِينَ هُمْ عَن صَلَاتِهِمْ سَاهُونَ" },
      { number: 6, text: "الَّذِينَ هُمْ يُرَاءُونَ" },
      { number: 7, text: "وَيَمْنَعُونَ الْمَاعُونَ" },
    ],
  },
  {
    number: 108,
    nameArabic: "الْكَوْثَر",
    nameTranslit: "Al-Kawthar",
    nameFr: "L'Abondance",
    versesCount: 3,
    verses: [
      { number: 1, text: "إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ" },
      { number: 2, text: "فَصَلِّ لِرَبِّكَ وَانْحَرْ" },
      { number: 3, text: "إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ" },
    ],
  },
  {
    number: 109,
    nameArabic: "الْكَافِرُون",
    nameTranslit: "Al-Kafirun",
    nameFr: "Les Mécréants",
    versesCount: 6,
    verses: [
      { number: 1, text: "قُلْ يَا أَيُّهَا الْكَافِرُونَ" },
      { number: 2, text: "لَا أَعْبُدُ مَا تَعْبُدُونَ" },
      { number: 3, text: "وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ" },
      { number: 4, text: "وَلَا أَنَا عَابِدٌ مَّا عَبَدتُّمْ" },
      { number: 5, text: "وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ" },
      { number: 6, text: "لَكُمْ دِينُكُمْ وَلِيَ دِينِ" },
    ],
  },
  {
    number: 110,
    nameArabic: "النَّصْر",
    nameTranslit: "An-Nasr",
    nameFr: "Le Secours",
    versesCount: 3,
    verses: [
      { number: 1, text: "إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ" },
      { number: 2, text: "وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا" },
      { number: 3, text: "فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ ۚ إِنَّهُ كَانَ تَوَّابًا" },
    ],
  },
  {
    number: 111,
    nameArabic: "الْمَسَد",
    nameTranslit: "Al-Masad",
    nameFr: "Les Fibres",
    versesCount: 5,
    verses: [
      { number: 1, text: "تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ" },
      { number: 2, text: "مَا أَغْنَىٰ عَنْهُ مَالُهُ وَمَا كَسَبَ" },
      { number: 3, text: "سَيَصْلَىٰ نَارًا ذَاتَ لَهَبٍ" },
      { number: 4, text: "وَامْرَأَتُهُ حَمَّالَةَ الْحَطَبِ" },
      { number: 5, text: "فِي جِيدِهَا حَبْلٌ مِّن مَّسَدٍ" },
    ],
  },
  {
    number: 112,
    nameArabic: "الْإِخْلَاص",
    nameTranslit: "Al-Ikhlas",
    nameFr: "Le Monothéisme Pur",
    versesCount: 4,
    verses: [
      { number: 1, text: "قُلْ هُوَ اللَّهُ أَحَدٌ" },
      { number: 2, text: "اللَّهُ الصَّمَدُ" },
      { number: 3, text: "لَمْ يَلِدْ وَلَمْ يُولَدْ" },
      { number: 4, text: "وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ" },
    ],
  },
  {
    number: 113,
    nameArabic: "الْفَلَق",
    nameTranslit: "Al-Falaq",
    nameFr: "L'Aube Naissante",
    versesCount: 5,
    verses: [
      { number: 1, text: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ" },
      { number: 2, text: "مِن شَرِّ مَا خَلَقَ" },
      { number: 3, text: "وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ" },
      { number: 4, text: "وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ" },
      { number: 5, text: "وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ" },
    ],
  },
  {
    number: 114,
    nameArabic: "النَّاس",
    nameTranslit: "An-Nas",
    nameFr: "Les Hommes",
    versesCount: 6,
    verses: [
      { number: 1, text: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ" },
      { number: 2, text: "مَلِكِ النَّاسِ" },
      { number: 3, text: "إِلَٰهِ النَّاسِ" },
      { number: 4, text: "مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ" },
      { number: 5, text: "الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ" },
      { number: 6, text: "مِنَ الْجِنَّةِ وَالنَّاسِ" },
    ],
  },
];

export interface BookmarkedVerse {
  surahNumber: number;
  verseNumber: number;
  surahNameArabic: string;
  surahNameTranslit: string;
  text: string;
}

export function getVerseKey(surahNumber: number, verseNumber: number): string {
  return `${surahNumber}:${verseNumber}`;
}

export function getSurah(number: number): Surah | undefined {
  return SURAHS.find((s) => s.number === number);
}
