// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-page/CompactCard.tsx": () => import("../components/mockups/landing-page/CompactCard.tsx"),
  "./components/mockups/landing-page/HeroCentered.tsx": () => import("../components/mockups/landing-page/HeroCentered.tsx"),
  "./components/mockups/landing-page/SplitScreen.tsx": () => import("../components/mockups/landing-page/SplitScreen.tsx")
};
